# ============================================================================
#  build_hls.tcl  --  Vitis HLS 2023.2: smi_pi.cpp -> block-design IP smi_pi
#
#  Builds the SMI power-inversion core (see smi_pi.cpp) and packages it as a
#  Vivado IP that Source/BlockDesign/system_bd.tcl instantiates as smi_pi_0,
#  in the AD9361 sample clock domain (axi_ad9361/l_clk, 8 ns).
#
#  Steps
#    1. C simulation, scenarios 1 (jammer null), 2 (no jammer), 3 (jammer on/off)
#       and 4 (weak jammer). Each needs a freshly reset core, so each is a
#       separate csim_design run.
#    2. C synthesis at an 8 ns target, II=2.
#    3. Checks the synthesis report: the pipeline must reach the requested II
#       and the estimated clock must not exceed the target. Otherwise the
#       script fails here instead of producing a bitstream that misses timing.
#    4. export_design -> $GNSS_CRPA_IP_REPO/smi_pi (default ../../../Build/ip_repo)
#
#  USAGE (from this directory)
#    vitis_hls -f build_hls.tcl
#
#  OVERRIDES (environment)
#    SMI_PI_CLK_NS=<ns>   HLS clock target, default 8
#    SMI_PI_II=<n>        pipeline II, default 2
#    SMI_PI_SKIP_CSIM=1   skip step 1
#    SMI_PI_K=<k>         averaging time constant 2^k samples, default 10
#
#  OUTPUT
#    $GNSS_CRPA_IP_REPO/smi_pi/component.xml, VLNV antsdr:gnss:smi_pi:1.0
#    $GNSS_CRPA_IP_REPO/smi_pi/smi_pi_csynth.rpt
#
#  SUCCESS MARKER
#    Prints "SMI_PI_HLS: PASS" only after the IP has been copied.
# ============================================================================

set here [file normalize [file dirname [info script]]]
set work [file join $here build]
if {[info exists ::env(GNSS_CRPA_IP_REPO)]} {
  set ip_repo [file normalize $::env(GNSS_CRPA_IP_REPO)]
} else {
  set ip_repo [file normalize [file join $here .. .. .. Build ip_repo]]
}
set out_ip [file join $ip_repo smi_pi]

# Same reasoning as Source/HLS/pi_nlms (LoopBack_Code): in the E310 2R2T LVDS
# mode the AD9361 interface delivers at most one sample pair every second
# l_clk, so II=2 loses nothing and gives each adaptive stage two clocks.
set clk_period 8
if {[info exists ::env(SMI_PI_CLK_NS)]} { set clk_period $::env(SMI_PI_CLK_NS) }
set pipeline_ii 2
if {[info exists ::env(SMI_PI_II)]} { set pipeline_ii $::env(SMI_PI_II) }
set clk_uncertainty 1.0
puts "SMI_PI_HLS: HLS clock target $clk_period ns (uncertainty $clk_uncertainty ns), II=$pipeline_ii"

file mkdir $work

# ---- source with the requested II -------------------------------------------
set fh  [open [file join $here smi_pi.cpp] r]
set src [read $fh]
close $fh
if {[regsub {#pragma HLS PIPELINE II=2} $src "#pragma HLS PIPELINE II=$pipeline_ii" src] != 1} {
  puts "SMI_PI_HLS: FAIL - expected one '#pragma HLS PIPELINE II=2' in smi_pi.cpp"
  exit 1
}
set hls_src [file join $work smi_pi_hls.cpp]
set fh [open $hls_src w]
puts -nonewline $fh "// GENERATED by build_hls.tcl from smi_pi.cpp -- do not edit.\n// Only the PIPELINE II may differ.\n$src"
close $fh

# ---- HLS project --------------------------------------------------------------
cd $work
open_project -reset smi_pi_hls
set_top smi_pi
# Averaging time constant 2^K samples (smi_pi.h, default 10).
set kdef ""
if {[info exists ::env(SMI_PI_K)]} { set kdef "-DSMI_PI_K=$::env(SMI_PI_K)" }
add_files $hls_src -cflags "-I$here $kdef"
add_files -tb [file join $here testbench.cpp] -cflags "-I$here $kdef -Wno-unknown-pragmas"
open_solution -reset sol -flow_target vivado
set_part {xc7z020clg400-2}
create_clock -period $clk_period -name default
set_clock_uncertainty $clk_uncertainty

# ---- 1 C simulation -------------------------------------------------------------
if {![info exists ::env(SMI_PI_SKIP_CSIM)] || $::env(SMI_PI_SKIP_CSIM) eq "0"} {
  foreach scen {1 2 3 4} {
    puts "SMI_PI_HLS: csim scenario $scen"
    if {[catch {csim_design -argv $scen} err]} {
      puts "SMI_PI_HLS: FAIL - C simulation scenario $scen: $err"
      exit 1
    }
  }
}

# ---- 2 C synthesis ---------------------------------------------------------------
csynth_design

# ---- 3 report checks -------------------------------------------------------------
set rpt_xml [file join $work smi_pi_hls sol syn report csynth.xml]
set rpt_txt [file join $work smi_pi_hls sol syn report smi_pi_csynth.rpt]
if {![file exists $rpt_xml]} {
  puts "SMI_PI_HLS: FAIL - synthesis report $rpt_xml not found"
  exit 1
}
set fh [open $rpt_xml r]
set xml [read $fh]
close $fh

set est ""
regexp {<EstimatedClockPeriod>([0-9.]+)</EstimatedClockPeriod>} $xml -> est
set ii ""
if {![regexp {<PipelineInitiationInterval>([0-9]+)</PipelineInitiationInterval>} $xml -> ii]} {
  regexp {<Interval-min>([0-9]+)</Interval-min>} $xml -> ii
}
puts "SMI_PI_HLS: estimated clock period $est ns (target $clk_period ns), achieved II $ii (requested $pipeline_ii)"
if {$est eq "" || $est > $clk_period} {
  puts "SMI_PI_HLS: FAIL - estimated clock period '$est' ns exceeds the $clk_period ns target"
  exit 1
}
if {$ii eq "" || $ii > $pipeline_ii} {
  puts "SMI_PI_HLS: FAIL - achieved II '$ii' is worse than the requested $pipeline_ii"
  exit 1
}

# ---- 4 package as a Vivado IP ------------------------------------------------------
export_design -format ip_catalog -rtl verilog \
  -vendor antsdr -library gnss -version 1.0 -ipname smi_pi \
  -display_name "SMI power inversion" \
  -description "Two-element closed-form SMI power-inversion anti-jam core (Vitis HLS). s_axis_x = RX1 and RX2 IQ, m_axis_y = RX1 minus a times RX2."

set impl_dir [file join $work smi_pi_hls sol impl]
set ip_src   [file join $impl_dir ip]
if {![file exists [file join $ip_src component.xml]]} {
  # Some releases leave only the zip; unpack it.
  set zips [glob -nocomplain -directory $impl_dir *.zip]
  if {[llength $zips] == 0} {
    puts "SMI_PI_HLS: FAIL - export_design produced no IP in $impl_dir"
    exit 1
  }
  file delete -force $ip_src
  file mkdir $ip_src
  exec unzip -q -o [lindex $zips 0] -d $ip_src
}
if {![file exists [file join $ip_src component.xml]]} {
  puts "SMI_PI_HLS: FAIL - no component.xml in $ip_src"
  exit 1
}

file mkdir $ip_repo
file delete -force $out_ip
file copy -force $ip_src $out_ip
if {[file exists $rpt_txt]} { file copy -force $rpt_txt $out_ip }

puts "SMI_PI_HLS: IP antsdr:gnss:smi_pi:1.0 -> $out_ip"
puts "SMI_PI_HLS: PASS"
exit 0
