# ============================================================================
#  build_rtl.tcl  --  Vitis HLS 2023.2: pi_nlms.cpp -> block-design IP
#
#  The original HLS project (PI_NLMS_hls) exports pi_nlms as a stand-alone
#  Vivado IP with its own AXI-Lite control bus.  In this design the core sits
#  in the block design next to gnss_passthrough (cell pi_nlms_0), in the
#  AD9361 sample clock domain, and gnss_passthrough already owns the register
#  interface and its clock-domain crossing.  So this script synthesises the
#  SAME C++ with one difference: mu_shift_ctrl and reserved_ctrl become plain
#  input ports (ap_none) instead of AXI-Lite registers, driven by
#  gnss_passthrough.  The algorithm, the AXI-Stream data ports and the
#  free-running control (ap_ctrl_none) are unchanged.
#
#  The interface change is made on a generated copy (build/pi_nlms_rtl.cpp);
#  pi_nlms.cpp stays the single, unmodified source of the algorithm.
#
#  USAGE (from this directory)
#    vitis_hls -f build_rtl.tcl
#
#  OUTPUT
#    $GNSS_CRPA_IP_REPO/pi_nlms/component.xml  (default ../../../Build/ip_repo)
#      VLNV antsdr:gnss:pi_nlms:1.0, instantiated by
#      Source/BlockDesign/system_bd.tcl as pi_nlms_0. Its Verilog is in
#      pi_nlms/hdl/verilog/.
#
#  SUCCESS MARKER
#    Prints "PI_NLMS_RTL: PASS" only after the IP has been copied.
# ============================================================================

set here    [file normalize [file dirname [info script]]]
set work    [file join $here build]
if {[info exists ::env(GNSS_CRPA_IP_REPO)]} {
  set ip_repo [file normalize $::env(GNSS_CRPA_IP_REPO)]
} else {
  set ip_repo [file normalize [file join $here .. .. .. Build ip_repo]]
}
set out_ip  [file join $ip_repo pi_nlms]

# Clock and initiation interval.
#
# axi_ad9361/l_clk is constrained at 8 ns (rx_clk in Source/XDC/system.xdc).
#
# The core keeps all of its adaptive state in static variables that are
# updated on every iteration, so with II=1 those feedback paths must close in
# ONE clock. At II=1 HLS estimated 7.93 ns whatever target it was given, and the
# routed design missed setup by 3.3 ns (reg_q2_term -> accum_grad_r). A tighter
# HLS clock cannot fix a single-cycle recurrence.
#
# II=2 gives those paths two cycles. It costs nothing here: in the 2R2T LVDS
# mode used on the E310, axi_ad9361_lvds_if.v asserts adc_valid only on the
# rx_frame 1111->0000 transition, i.e. at most every 2nd l_clk. One sample pair
# per two clocks is therefore the most the core can ever be offered.
# gnss_passthrough flags any pair the core could not accept in STATUS[10].
#
# Overrides:  PI_NLMS_CLK_NS=<ns>  PI_NLMS_II=<n>
set clk_period 8
if {[info exists ::env(PI_NLMS_CLK_NS)]} { set clk_period $::env(PI_NLMS_CLK_NS) }
set pipeline_ii 2
if {[info exists ::env(PI_NLMS_II)]} { set pipeline_ii $::env(PI_NLMS_II) }
set clk_uncertainty 1.0
puts "PI_NLMS_RTL: HLS clock target $clk_period ns (uncertainty $clk_uncertainty ns), II=$pipeline_ii"

file mkdir $work

# ---- derive the RTL-variant source ----------------------------------------
set fh  [open [file join $here pi_nlms.cpp] r]
set src [read $fh]
close $fh

set n 0
incr n [regsub {#pragma HLS INTERFACE s_axilite port=mu_shift_ctrl[^\n]*} $src \
          {#pragma HLS INTERFACE ap_none port=mu_shift_ctrl} src]
incr n [regsub {#pragma HLS INTERFACE s_axilite port=reserved_ctrl[^\n]*} $src \
          {#pragma HLS INTERFACE ap_none port=reserved_ctrl} src]
incr n [regsub {#pragma HLS INTERFACE s_axilite port=return[^\n]*\n} $src {} src]
if {$n != 3} {
  puts "PI_NLMS_RTL: FAIL - expected 3 s_axilite pragmas in pi_nlms.cpp, replaced $n"
  exit 1
}
if {[regsub {#pragma HLS PIPELINE II=1} $src "#pragma HLS PIPELINE II=$pipeline_ii" src] != 1} {
  puts "PI_NLMS_RTL: FAIL - expected one '#pragma HLS PIPELINE II=1' in pi_nlms.cpp"
  exit 1
}

set rtl_src [file join $work pi_nlms_rtl.cpp]
set fh [open $rtl_src w]
puts -nonewline $fh "// GENERATED by build_rtl.tcl from pi_nlms.cpp -- do not edit.\n// Only the INTERFACE pragmas (mu_shift_ctrl/reserved_ctrl/return) and the\n// PIPELINE II differ.\n$src"
close $fh

# ---- HLS ------------------------------------------------------------------
cd $work
open_project -reset pi_nlms_rtl
set_top pi_nlms
add_files $rtl_src -cflags "-I$here"
add_files -tb [file join $here testbench.cpp] -cflags "-I$here -Wno-unknown-pragmas"
open_solution -reset sol -flow_target vivado
set_part {xc7z020clg400-2}
create_clock -period $clk_period -name default
set_clock_uncertainty $clk_uncertainty

csim_design
csynth_design

# ---- package as a Vivado IP ------------------------------------------------
export_design -format ip_catalog -rtl verilog \
  -vendor antsdr -library gnss -version 1.0 -ipname pi_nlms \
  -display_name "PI-NLMS null steering" \
  -description "Two-element PI-NLMS anti-jam core (Vitis HLS). in1 = RX1, in2 = RX2, out_r = null-steered output."

set impl_dir [file join $work pi_nlms_rtl sol impl]
set ip_src   [file join $impl_dir ip]
if {![file exists [file join $ip_src component.xml]]} {
  # Some releases leave only the zip; unpack it.
  set zips [glob -nocomplain -directory $impl_dir *.zip]
  if {[llength $zips] == 0} {
    puts "PI_NLMS_RTL: FAIL - export_design produced no IP in $impl_dir"
    exit 1
  }
  file delete -force $ip_src
  file mkdir $ip_src
  exec unzip -q -o [lindex $zips 0] -d $ip_src
}
if {![file exists [file join $ip_src component.xml]]} {
  puts "PI_NLMS_RTL: FAIL - no component.xml in $ip_src"
  exit 1
}

file mkdir $ip_repo
file delete -force $out_ip
file copy -force $ip_src $out_ip
file copy -force [file join $work pi_nlms_rtl sol syn report pi_nlms_csynth.rpt] $out_ip

puts "PI_NLMS_RTL: IP antsdr:gnss:pi_nlms:1.0 -> $out_ip"
puts "PI_NLMS_RTL: PASS"
exit 0
