# ============================================================================
#  create_project.tcl  --  reconstruct the Vivado project from maintained source
#
#  This is the ONLY way the Vivado project is created (requirements 11, 12).
#  There is no second, automation-private design: the .xpr produced here is the
#  same one an engineer opens in the GUI (requirements 13, 24).
#
#  The project REFERENCES the files under Source/ rather than importing copies,
#  because adi_project_files uses "add_files -norecurse".  Editing
#  Source/HDL/system_top.v in the Vivado GUI therefore edits the authoritative
#  file directly, and a change made by a script is visible the moment the
#  project is reopened (requirements 9, 10, 68).
#
#  The block design is the one exception: Vivado owns the generated .bd inside
#  the project.  It is rebuilt from Source/BlockDesign/system_bd.tcl every time
#  this script runs, and GUI edits are pushed back with export_bd_to_source.tcl
#  (requirement 67).
#
#  REQUIRED ENVIRONMENT (set by Automation/Linux/build_all.sh)
#    GNSS_CRPA_ROOT           absolute path of LoopBack_Code
#    GNSS_CRPA_IP_REPO        absolute path of the packaged custom IP repo
#    ADI_HDL_DIR              absolute path of the working copy of the ADI tree
#                             (Build/VendorWork/hdl, copied from
#                             Vendor/ADI_hdl_2023_r2)
#    REQUIRED_VIVADO_VERSION  optional; hdl_2023_r2 already expects 2023.2
#
#  TOOL VERSION
#    This project targets Vivado 2023.2 together with the Analog Devices
#    hdl_2023_r2 release, which ADI build and test against 2023.2.  The script
#    warns (it does not stop) if it is run under any other version.
#
#  The script refuses to run rather than guess any of them (requirements 31, 32).
# ============================================================================

foreach v {GNSS_CRPA_ROOT GNSS_CRPA_IP_REPO ADI_HDL_DIR} {
  if {![info exists ::env($v)]} {
    puts "CREATE_RESULT: FAIL - required environment variable $v is not set"
    exit 2
  }
}

set root    [file normalize $::env(GNSS_CRPA_ROOT)]
set adi_dir [file normalize $::env(ADI_HDL_DIR)]
set proj    "antsdr_e310_gnss"

# adi_env.tcl moved from projects/scripts/ to scripts/ in the modern Analog
# Devices releases. Accept either so the project is not tied to one layout.
set adi_env ""
foreach cand [list "$adi_dir/scripts/adi_env.tcl" "$adi_dir/projects/scripts/adi_env.tcl"] {
  if {[file exists $cand]} { set adi_env $cand; break }
}
if {$adi_env eq ""} {
  puts "CREATE_RESULT: FAIL - adi_env.tcl not found under $adi_dir"
  puts "CREATE_HINT: looked in scripts/ and projects/scripts/"
  exit 2
}

foreach f [list \
    "$root/Source/HDL/system_top.v" \
    "$root/Source/XDC/system.xdc" \
    "$root/Source/BlockDesign/system_bd.tcl" \
    "$adi_dir/library/common/ad_iobuf.v" ] {
  if {![file exists $f]} {
    puts "CREATE_RESULT: FAIL - required source missing: $f"
    exit 2
  }
}

source $adi_env

set target_vivado "2023.2"
set running_vivado [version -short]
if {![string match "${target_vivado}*" $running_vivado]} {
  puts "CREATE_WARNING: this project targets Vivado $target_vivado, running $running_vivado"
} else {
  puts "CREATE_VIVADO: $running_vivado"
}
source $ad_hdl_dir/projects/scripts/adi_project_xilinx.tcl
source $ad_hdl_dir/projects/scripts/adi_board.tcl

# adi_project_create does "create_project <name> ." and then "source
# system_bd.tcl", both relative to the current directory.  The caller has
# already cd'd into Vivado/Project.  Emit a one-line shim there that redirects
# to the authoritative block design, so the generated project directory holds
# no design content of its own.
set shim [open "system_bd.tcl" w]
puts $shim "# GENERATED by Vivado/Scripts/create_project.tcl - do not edit."
puts $shim "# The authoritative block design is Source/BlockDesign/system_bd.tcl."
puts $shim "source \[file normalize \"$root/Source/BlockDesign/system_bd.tcl\"\]"
close $shim

set p_device "xc7z020clg400-2"

# ---------------------------------------------------------------------------
#  Timing closure aids for an AD9361 design on Zynq-7000.
#
#  The first successful build of this design closed neither setup nor hold
#  (WNS -1.621 ns, WHS -1.153 ns). Analog Devices ship two remedies for exactly
#  this situation and both are adopted here:
#
#    auto_timing_fix_xilinx.tcl  runs after routing and iterates phys_opt_design
#                                to clean up violations. Its own header notes
#                                that when a HOLD violation is present it calls
#                                route_design again "as a workaround for Vivado
#                                2024.x/2025.x hold timing issues" -- which is
#                                the class of problem seen here.
#
#    Congestion_SpreadLogic_high is the strategy ADI's own fmcomms2 projects
#                                use, with the comment "fmcomms2 design is
#                                presenting hold time violations on some paths".
#                                fmcomms2 is the closest reference design to
#                                this one: same AD9361, same Zynq-7000 class.
#
#  ADI_POST_ROUTE_SCRIPT must be set BEFORE adi_project_files, which is what
#  adds it to the utils_1 fileset.
# ---------------------------------------------------------------------------
#
#  Vivado 2023.2 note: auto_timing_fix_xilinx.tcl first shipped in the ADI
#  2025 releases, so hdl_2023_r2 does not contain it, and its
#  adi_project_files does not know about ADI_POST_ROUTE_SCRIPT either.  A copy
#  is kept next to this script and is used whenever the vendor tree lacks one;
#  it only calls route_design / phys_opt_design / report_timing_summary, all of
#  which behave the same in 2023.2.  The file is added to utils_1 explicitly
#  below, after adi_project_files.
# ---------------------------------------------------------------------------
set ADI_POST_ROUTE_SCRIPT [file normalize $ad_hdl_dir/projects/scripts/auto_timing_fix_xilinx.tcl]
if {![file exists $ADI_POST_ROUTE_SCRIPT]} {
  set ADI_POST_ROUTE_SCRIPT [file normalize [file join [file dirname [info script]] auto_timing_fix_xilinx.tcl]]
}
if {![file exists $ADI_POST_ROUTE_SCRIPT]} {
  puts "CREATE_RESULT: FAIL - post-route timing script missing: $ADI_POST_ROUTE_SCRIPT"
  exit 2
}
puts "CREATE_POST_ROUTE_SCRIPT: $ADI_POST_ROUTE_SCRIPT"

adi_project $proj

adi_project_files $proj [list \
  "$ad_hdl_dir/library/common/ad_iobuf.v" \
  "$root/Source/XDC/system.xdc" \
  "$root/Source/XDC/gnss_passthrough_cdc.xdc" \
  "$root/Source/HDL/system_top.v" ]

# hdl_2023_r2's adi_project_files does not add ADI_POST_ROUTE_SCRIPT to the
# utils_1 fileset (later ADI releases do).  Add it here if it is not there yet.
if {[llength [get_files -quiet $ADI_POST_ROUTE_SCRIPT -of [get_filesets utils_1]]] == 0} {
  add_files -fileset utils_1 -norecurse $ADI_POST_ROUTE_SCRIPT
}

# The CDC constraints reference cells inside the block design, so they must be
# evaluated after the design's own clocks and hierarchy exist.
set gnss_cdc_xdc [get_files -quiet "$root/Source/XDC/gnss_passthrough_cdc.xdc"]
if {[llength $gnss_cdc_xdc] == 0} {
  puts "CREATE_RESULT: FAIL - gnss_passthrough_cdc.xdc was not added to the project"
  exit 2
}
set_property PROCESSING_ORDER LATE $gnss_cdc_xdc
puts "CREATE_CDC_XDC: gnss_passthrough_cdc.xdc added with PROCESSING_ORDER LATE"

# This project drives implementation from Vivado/Scripts/build.tcl rather than
# adi_project_run, so the run properties adi_project_run would have set must be
# applied here instead.
set_property strategy Congestion_SpreadLogic_high [get_runs impl_1]
set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.ROUTE_DESIGN.TCL.POST \
  [get_files $ADI_POST_ROUTE_SCRIPT -of [get_fileset utils_1]] [get_runs impl_1]
puts "CREATE_TIMING_AIDS: strategy=Congestion_SpreadLogic_high, post-route auto timing fix enabled"

# Vivado 2023.2 automatic incremental synthesis registers the previous run's
# checkpoint under utils_1/imports/synth_1 after every synthesis. On this flow
# that step failed ("set_property expects at least one object", which marked
# a COMPLETED synth_1 as failed) and the next build then refused to start
# ("Incremental checkpoint file ... does not exist"). Builds here are always
# from scratch, so switch it off.
foreach run [list synth_1 impl_1] {
  catch {set_property AUTO_INCREMENTAL_CHECKPOINT 0 [get_runs $run]}
  catch {set_property INCREMENTAL_CHECKPOINT {} [get_runs $run]}
}
puts "CREATE_INCREMENTAL: automatic incremental checkpoints disabled"

# Record where the design came from, visible in the Vivado GUI project summary.
set_property generic {} [current_fileset]

puts "CREATE_PROJECT_PART: [get_property part [current_project]]"
puts "CREATE_PROJECT_XPR:  [get_property directory [current_project]]/$proj.xpr"
puts "CREATE_RESULT: PASS"
exit 0
