`timescale 1ns/1ps
// icepi_clk_wiz_video : Lattice ECP5 PLL wrapper, 50 MHz -> 25 MHz pixel
// clock + 125 MHz TMDS shift clock (5x pixel clock), both taken from a
// single EHXPLLL instance so they share one VCO and have a fixed,
// deterministic phase relationship - tmds_serializer.v depends on this:
// it uses shift_clk's free-running mod-5 counter to know which slice of
// the current pixel is being sent, with no CDC synchronizer between the
// two clocks, which is only safe because they are locked, integer
// multiples of the same VCO with zero dynamic phase adjustment.
//
// Target ratios this PLL must be generated for:
//   CLKOP (pixel clock)      = 25 MHz  = CLKI * CLKFB_DIV / CLKI_DIV
//   CLKOS (TMDS shift clock) = 125 MHz = 5 x CLKOP
//
// The `else` branch below IS a real, synthesizable EHXPLLL
// configuration - CLKI_DIV=2/CLKFB_DIV=1 gives CLKOP=25MHz exactly,
// and CLKOP_DIV=20/CLKOS_DIV=4 place the VCO at 500 MHz (a normal
// operating point for this PLL) while giving CLKOS=125MHz exactly.
// These parameters were hand-derived from the EHXPLLL divider
// equations, not generated by Diamond's Clarity Designer (Diamond
// wasn't available while writing this project), so while they should
// build and lock correctly, **regenerating this with Clarity Designer
// is still the recommended way to get a Diamond-verified netlist**
// before treating this as final:
//
//   1. Tools -> Clarity Designer -> Clocking -> PLL
//   2. Module/Output Name : icepi_clk_wiz_video   (must match exactly -
//      this is the module name sd_image_hdmi_top.v instantiates)
//   3. Frequency tab: CLKI = 50 MHz, CLKOP = 25 MHz,
//      feedback = internal/CLKOP
//   4. Frequency tab: also enable CLKOS, set CLKOS = 125 MHz
//   5. Optional Ports tab: enable ONLY "Provide PLL Lock Signal"
//      (leave "PLL Lock is Sticky" and "Provide PLL Reset" unchecked -
//      this design never resets the PLL itself, only watches LOCK)
//   6. Generate. Diamond writes a file (commonly named
//      icepi_clk_wiz_video_1.v, or similar - check the generated file
//      list) containing `module icepi_clk_wiz_video (...)` with ports
//      CLKI/CLKOP/CLKOS/LOCK, matching this wrapper's port list below
//      exactly.
//   7. Replace everything between `else` and `` `endif `` below with
//      the BODY of Diamond's generated module - i.e. keep this file's
//      `` `ifdef SIMULATION ``/`` `else ``/`` `endif `` structure and
//      module declaration, only swapping the internals. Do not add
//      Diamond's generated file as a second, separate project source -
//      that would create a duplicate `icepi_clk_wiz_video` module
//      definition.
//
// This is exactly the procedure already used for icepi_clk_wiz.v (the
// sys_clk PLL reused from the sd_uart_top project earlier in this
// bring-up) - see that project's README for the same steps applied to
// a real board and toolchain.
module icepi_clk_wiz_video (
    input  wire CLKI,       // 50 MHz oscillator input
    output wire CLKOP,      // 25 MHz pixel clock
    output wire CLKOS,      // 125 MHz TMDS shift clock (5x CLKOP)
    output wire LOCK        // PLL LOCK status
);

`ifdef SIMULATION
    // Behavioral stand-in for simulation only (EHXPLLL has no generic
    // Verilog simulation model outside Diamond/Lattice libraries).
    // Measures CLKI's period from its first two edges, then free-runs
    // CLKOP at that period x2 (50->25 MHz) and CLKOS at that period x0.4
    // (50->125 MHz), keeping the intended 5:1 CLKOS:CLKOP ratio exactly.
    reg     clkop_r = 1'b0;
    reg     clkos_r = 1'b0;
    reg     locked_r = 1'b0;
    integer lock_cnt = 0;
    real    clkin_period_ns;
    real    t_prev = 0.0;
    reg     period_known = 1'b0;

    always @(posedge CLKI) begin
        if (!period_known) begin
            if (t_prev != 0.0) begin
                clkin_period_ns <= $realtime - t_prev;
                period_known    <= 1'b1;
            end
            t_prev <= $realtime;
        end
        if (lock_cnt < 200)
            lock_cnt <= lock_cnt + 1;
        else
            locked_r <= 1'b1;
    end

    initial begin
        clkop_r = 1'b0;
        wait (period_known);
        forever #(clkin_period_ns * 1.0) clkop_r = ~clkop_r; // /2 toggle -> 25 MHz from 50 MHz
    end

    initial begin
        clkos_r = 1'b0;
        wait (period_known);
        forever #(clkin_period_ns * 0.2) clkos_r = ~clkos_r; // x5 rate -> 125 MHz from 50 MHz
    end

    assign CLKOP = clkop_r;
    assign CLKOS = clkos_r;
    assign LOCK  = locked_r;
`else
    // Hand-derived EHXPLLL configuration - see header comment above
    // for the exact ratios and the recommended Clarity Designer
    // regeneration steps. This is a real, complete PLL instantiation
    // (not a stub), synthesizable as shipped.
    wire CLKFB_t;
    wire scuba_vhi;
    wire scuba_vlo;

    // Tied directly instead of instantiating VHI/VLO primitive modules:
    // some OSS CAD Suite builds already define VHI/VLO inside synth_ecp5's
    // own ECP5 cell library (share/yosys/lattice/cells_sim_ecp5.v), which
    // collides ("Re-definition of module") with a same-named stub module
    // read in separately. A plain tie has no name to collide on any build.
    assign scuba_vhi = 1'b1;
    assign scuba_vlo = 1'b0;

    defparam PLLInst_0.PLLRST_ENA = "DISABLED" ;
    defparam PLLInst_0.INTFB_WAKE = "DISABLED" ;
    defparam PLLInst_0.STDBY_ENABLE = "DISABLED" ;
    defparam PLLInst_0.DPHASE_SOURCE = "DISABLED" ;
    defparam PLLInst_0.CLKOS3_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS3_CPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_CPHASE = 0 ;
    defparam PLLInst_0.CLKOS_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS_CPHASE = 0 ;
    defparam PLLInst_0.CLKOP_FPHASE = 0 ;
    defparam PLLInst_0.CLKOP_CPHASE = 19 ;
    defparam PLLInst_0.PLL_LOCK_MODE = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOP_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.OUTDIVIDER_MUXD = "DIVD" ;
    defparam PLLInst_0.CLKOS3_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXC = "DIVC" ;
    defparam PLLInst_0.CLKOS2_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXB = "DIVB" ;
    defparam PLLInst_0.CLKOS_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXA = "DIVA" ;
    defparam PLLInst_0.CLKOP_ENABLE = "ENABLED" ;
    defparam PLLInst_0.CLKOS3_DIV = 1 ;
    defparam PLLInst_0.CLKOS2_DIV = 1 ;
    defparam PLLInst_0.CLKOS_DIV = 4 ;
    defparam PLLInst_0.CLKOP_DIV = 20 ;
    defparam PLLInst_0.CLKFB_DIV = 1 ;
    defparam PLLInst_0.CLKI_DIV = 2 ;
    defparam PLLInst_0.FEEDBK_PATH = "CLKOP" ;
    EHXPLLL PLLInst_0 (.CLKI(CLKI), .CLKFB(CLKFB_t), .PHASESEL1(scuba_vlo),
        .PHASESEL0(scuba_vlo), .PHASEDIR(scuba_vlo), .PHASESTEP(scuba_vlo),
        .PHASELOADREG(scuba_vlo), .STDBY(scuba_vlo), .PLLWAKESYNC(scuba_vlo),
        .RST(scuba_vlo), .ENCLKOP(scuba_vlo), .ENCLKOS(scuba_vlo), .ENCLKOS2(scuba_vlo),
        .ENCLKOS3(scuba_vlo), .CLKOP(CLKFB_t), .CLKOS(CLKOS), .CLKOS2(), .CLKOS3(),
        .LOCK(LOCK), .INTLOCK(), .REFCLK(), .CLKINTFB())
             /* synthesis FREQUENCY_PIN_CLKOP="25.000000" */
             /* synthesis FREQUENCY_PIN_CLKOS="125.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="50.000000" */
             /* synthesis ICP_CURRENT="5" */
             /* synthesis LPF_RESISTOR="16" */;

    assign CLKOP = CLKFB_t;
`endif

endmodule
