`timescale 1ns/1ps
// icepi_clk_wiz_sys : Lattice ECP5 PLL wrapper, 50 MHz -> 20 MHz.
//
// Unlike icepi_clk_wiz_video.v in this same project, the `else` branch
// below is NOT a placeholder - it's reused verbatim from the
// sd_uart_top project's icepi_clk_wiz.v (only the outer module name
// was changed, to icepi_clk_wiz_sys, so it can coexist in this project
// alongside icepi_clk_wiz_video.v), which IS real, Diamond-Clarity-
// Designer-generated output that was actually synthesized and brought
// up on real IcePi Zero hardware during that earlier project - see
// that project's README for the build/bring-up results. Since the
// spec here is identical (same board, same 50 MHz -> 20 MHz single-
// output PLL), that verified content is left in place rather than
// downgraded to a placeholder that would just make you redo work
// you've already done and tested.
//
// If you'd still rather regenerate this fresh specifically for the
// sd_image_hdmi project (e.g. for a clean project-local .fdc path -
// the SCUBA comment below still references the original project's
// path, which is cosmetic only and doesn't affect synthesis), follow
// the same Clarity Designer procedure documented in
// icepi_clk_wiz_video.v's header comment, with Module/Output Name set
// to icepi_clk_wiz_sys, CLKOP = 20 MHz, and no CLKOS output enabled.
//
// The `else` branch is the exact, unmodified body of Lattice Diamond's
// Clarity Designer "PLL" generator output (SCUBA, Diamond
// 3.14.0.75.2), targeting LFE5U-25F-6BG256C, CLKI=50.00MHz /
// CLKOP=20.00MHz / internal CLKOP feedback / PLL Lock Signal enabled,
// non-sticky, no PLL RST port.
module icepi_clk_wiz_sys (
    input  wire CLKI,   // 50 MHz oscillator input
    output wire CLKOP,  // 20 MHz system clock output
    output wire LOCK    // PLL LOCK status
);

`ifdef SIMULATION
    // Behavioral stand-in for simulation only (EHXPLLL has no generic
    // Verilog simulation model outside Diamond/Lattice libraries).
    // Produces a 20 MHz clock from the 50 MHz input using a 5:2
    // fractional toggle pattern, and asserts LOCK after a short delay,
    // matching real PLL lock-time behavior closely enough for RTL sim.
    // (CLKOP frequency depends only on CLKFB_DIV/CLKI_DIV = 2/5; the
    // VCO operating point chosen by CLKOP_DIV in the synthesis branch
    // below is an internal implementation detail that doesn't change
    // this ratio, so the simulation model needs no adjustment for it.)
    reg     clkout_r = 1'b0;
    reg     locked_r = 1'b0;
    integer lock_cnt = 0;
    real    clkin_period_ns;
    real    t_prev = 0.0;
    reg     period_known = 1'b0;

    always @(posedge CLKI) begin
        if (!period_known) begin
            if (t_prev != 0.0) begin
                clkin_period_ns <= $realtime - t_prev;
                period_known    <= 1'b1;
            end
            t_prev <= $realtime;
        end
        if (lock_cnt < 200)
            lock_cnt <= lock_cnt + 1;
        else
            locked_r <= 1'b1;
    end

    initial begin
        clkout_r = 1'b0;
        wait (period_known);
        forever #(clkin_period_ns * 1.25) clkout_r = ~clkout_r;
    end

    assign CLKOP = clkout_r;
    assign LOCK  = locked_r;
`else
    /* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
    /* Module Version: 5.7 */
    /* /opt/lscc/ispfpga/bin/lin64/scuba -w -n icepi_clk_wiz -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type pll -fin 50.00 -fclkop 20.00 -fclkop_tol 0.0 -phase_cntl STATIC -lock -fb_mode 1 -fdc /home/sandeep/Downloads/ICEPI-ZERO_All/Lattice_Testing_5/icepi_zero/icepi_clk_wiz/icepi_clk_wiz.fdc  */

    wire REFCLK;
    wire CLKOP_t;
    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PLLInst_0.PLLRST_ENA = "DISABLED" ;
    defparam PLLInst_0.INTFB_WAKE = "DISABLED" ;
    defparam PLLInst_0.STDBY_ENABLE = "DISABLED" ;
    defparam PLLInst_0.DPHASE_SOURCE = "DISABLED" ;
    defparam PLLInst_0.CLKOS3_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS3_CPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_CPHASE = 0 ;
    defparam PLLInst_0.CLKOS_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS_CPHASE = 0 ;
    defparam PLLInst_0.CLKOP_FPHASE = 0 ;
    defparam PLLInst_0.CLKOP_CPHASE = 28 ;
    defparam PLLInst_0.PLL_LOCK_MODE = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOP_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.OUTDIVIDER_MUXD = "DIVD" ;
    defparam PLLInst_0.CLKOS3_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXC = "DIVC" ;
    defparam PLLInst_0.CLKOS2_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXB = "DIVB" ;
    defparam PLLInst_0.CLKOS_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXA = "DIVA" ;
    defparam PLLInst_0.CLKOP_ENABLE = "ENABLED" ;
    defparam PLLInst_0.CLKOS3_DIV = 1 ;
    defparam PLLInst_0.CLKOS2_DIV = 1 ;
    defparam PLLInst_0.CLKOS_DIV = 1 ;
    defparam PLLInst_0.CLKOP_DIV = 29 ;
    defparam PLLInst_0.CLKFB_DIV = 2 ;
    defparam PLLInst_0.CLKI_DIV = 5 ;
    defparam PLLInst_0.FEEDBK_PATH = "CLKOP" ;
    EHXPLLL PLLInst_0 (.CLKI(CLKI), .CLKFB(CLKOP_t), .PHASESEL1(scuba_vlo),
        .PHASESEL0(scuba_vlo), .PHASEDIR(scuba_vlo), .PHASESTEP(scuba_vlo),
        .PHASELOADREG(scuba_vlo), .STDBY(scuba_vlo), .PLLWAKESYNC(scuba_vlo),
        .RST(scuba_vlo), .ENCLKOP(scuba_vlo), .ENCLKOS(scuba_vlo), .ENCLKOS2(scuba_vlo),
        .ENCLKOS3(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(), .CLKOS2(), .CLKOS3(),
        .LOCK(LOCK), .INTLOCK(), .REFCLK(REFCLK), .CLKINTFB())
             /* synthesis FREQUENCY_PIN_CLKOP="20.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="50.000000" */
             /* synthesis ICP_CURRENT="5" */
             /* synthesis LPF_RESISTOR="16" */;

    assign CLKOP = CLKOP_t;

    // exemplar begin
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 20.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 50.000000
    // exemplar attribute PLLInst_0 ICP_CURRENT 5
    // exemplar attribute PLLInst_0 LPF_RESISTOR 16
    // exemplar end
`endif

endmodule
